swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"  # Version of our API
  title: Mensa-App
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application and our endpoints
paths:
  /menu:
    get:
      operationId: menu.read_all
      tags:
        - Menu
      summary: Read the entire list of menu
      description: Read the list of menu
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of items of menu to get from menu
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering menu
          required: false
      responses:
        200:
          description: Successfully read menu list operation
          schema:
            type: array
            items:
              properties:
                meal:
                  type: string
                price:
                  type: string
                timestamp:
                  type: string
                count:
                  type: string

    post:
      operationId: menu.create
      tags:
        - Menu
      summary: Create food and add it to the menu list
      description: Create new food in the menu list
      parameters:
        - name: food
          in: body
          description: food to create
          required: True
          schema:
            type: object
            properties:
              meal:
                type: string
                description: name of meal to create
              price:
                type: string
                description: price of food to create
              count:
                type: string
                description: number of orders
      responses:
        201:
          description: Successfully created food in list

  /menu/{price}:
    get:
      operationId: menu.read_one
      tags:
        - Menu
      summary: Read food from the menu list
      description: Read  food from the menu list
      parameters:
        - name: price
          in: path
          description: price of the food to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read food from menu list operation
          schema:
            properties:
              meal:
                type: string
              price:
                type: string
              timestamp:
                type: string
              count:
                type: string

    put:
      operationId: menu.update
      tags:
        - Menu
      summary: Update a food in the menu list
      description: Update a food in the menu list
      parameters:
        - name: price
          in: path
          description: price of the food to update in the list
          type: string
          required: True
        - name: food
          in: body
          schema:
            type: object
            properties:
              meal:
                type: string
              price:
                type: string
      responses:
        200:
          description: Successfully updated food in menu list

    delete:
      operationId: menu.delete
      tags:
        - Menu
      summary: Delete  food from the menu list
      description: Delete  food
      parameters:
        - name: price
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted food from menu list